"""Add nested forum replies

Revision ID: 42f01ca82d08
Revises: 68df065c47eb
Create Date: 2026-05-13 20:37:49.985050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f01ca82d08'
down_revision = '68df065c47eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_forum_replies_parent_id_forum_replies",
            "forum_replies",
            ["parent_id"],
            ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_replies', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_forum_replies_parent_id_forum_replies",
            type_="foreignkey"
        )
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
